#!/bin/bash

# silence the world-writable warnings about my external disk by mac os system ruby
export RUBYOPT="-W0"

# install the tools I need directly from source and place them in their scripting home
s_ruby=$(which sysruby)
s_rake=$(which sysrake)

if [[ ! -x "${s_ruby}" ]]; then
    echo "sysruby does not exist, exiting" && exit 1
fi

if [[ ! -x "${s_rake}" ]]; then
    echo "sysrake does exist, exiting" && exit 1
fi

${s_rake} srcinstall
